# Generated by Django 2.0 on 2018-01-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nube', '0002_cloudimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudimage',
            name='name',
            field=models.CharField(default='untitled', max_length=50),
        ),
    ]
